name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Kubernetes
      uses: azure/setup-kubectl@v3

    - name: Apply Kubernetes Manifests
      run: |
        kubectl apply -f apps/myapp.yaml
