apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/mrgpr10/gitops-project-01.git
    path: apps
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
